from General_Functions import Procesar_configuracion

# Abrimos el archivo de configuración del proyecto.
config = Procesar_configuracion(nom_archivo_configuracion="config.yml")

# Tipos de clientes
ACTIVOS = config["ACTIVOS"]
INACTIVOS = config["INACTIVOS"]

# Socios
SOCIOS = config["SOCIOS"]
FILTRAR_SOCIOS = config["FILTRAR_SOCIOS"]
# Biblia
BIBLIA = config["BIBLIA"]
ACUERDO  = config["ACUERDO"]
ESTADO_FINAL = config["ESTADO_FINAL"]
META = config["META"]
PERIODO = config["PERIODO"]
INVERSION = config["INVERSION"]
BENEFICIO = config["BENEFICIO"]

# Estructura Ventas
ESTRUCTURA_VENTAS = config["ESTRUCTURA_VENTAS"]
NOM_VENDEDOR_1 = config["CONSTANTES_EV"]["NOM_VENDEDOR_1"]
COD_JEFE_VENTAS = config["CONSTANTES_EV"]["COD_JEFE_VENTAS"]
NOM_JEFE_VENTAS = config["CONSTANTES_EV"]["NOM_JEFE_VENTAS"]
COD_VENDEDOR = config["CONSTANTES_EV"]["COD_VENDEDOR"]
NOM_FIGURA_COMER = config["CONSTANTES_EV"]["NOM_FIGURA_COMER"]
COD_FIGURA_COMER = config["CONSTANTES_EV"]["COD_FIGURA_COMER"]
DICT_CN_TIP_GC = config["dict_cn_tip_gc"]
DICT_SUBCN_TIP_TI_DROG = config["dict_subcn_tip_ti_dro"]


# BO Acumulado
BO_ACUMULADO = config["BO_ACUMULADO"]
# BO Trimestre
BO_TRIMESTRE = config["BO_TRIMESTRE"]
# BO Mes
BO_MES = config["BO_MES"]
# Nuevos nombre cols
NUEVAS_COLS_BO = config["Dict_columnas_bo"]

# AFO consulta inversion clientes
AFO_CONSUL_INV = config["AFO_CONSUL_INV"]
# Consolidado gastos clientes
COLS_AGRUP_CONS_GASTOS = config["COLS_AGRUP_CONS_GASTOS"]
# Historico_bd_gastos
HISTORI_BD_GASTOS = config["HISTORI_BD_GASTOS"]

# Anexos
ANEXOS = config["ANEXOS"]

BD_CLIENTES_MES_ANT = config["BD_CLIENTES_MES_ANT"]

# Rutas insumos
RUTA_INSUMOS = config["path"]["Insumos"]
RUTA_INSUMOS_P2 = config["path"]["Insumos_P2"]
RUTA_DRIVERS = config["path"]["Drivers"]
RUTA_BASES_BO = config["path"]["BasesBO"]
RESULTADOS_P2 = config["path"]["Resultados"]["RESULTADOS_P2"]
RESULTADOS_P1 = config["path"]["Resultados"]["RESULTADOS_P1"]
RESULTADOS_P3 = config["path"]["Resultados"]["RESULTADOS_P3"]
RESULTADOS_P4 = config["path"]["Resultados"]["RESULTADOS_P4"]
RESULTADOS_P6 = config["path"]["Resultados"]["RESULTADOS_P6"]
RESULTADOS_P7 = config["path"]["Resultados"]["RESULTADOS_P7"]

# Constantes lectura
INSUMOS = config["Insumos"]
INSUMOS_P2 = config["Insumos_P2"]
NOM_DRIVER_GENERADO = config["NOM_DRIVER_GENERADO"]
NOM_DRIVER_USUARIO = config["NOM_DRIVER_USUARIO"]
FILE_NAME = config["FILE_NAME"]
SHEET = config["SHEET"]
NUM_SHEET = config["NUM_SHEET"]
COLS = config["COLS"]
COLS_NECESARIAS = config["COLS_NECESARIAS"]
RENOMBRAR_COLUMNAS = config["RENOMBRAR_COLS"]

# Columnas posibles necesarias de los dataframes.
NIT = config["NIT"]
NIF = config["NIF"]
NIF_ORIG = config["NIF_ORIG"]
MES = config["MES"]
MES_ORIG = config["MES_ORIG"]
CANAL = config["CANAL"]
COD_LOC = config["COD_LOC"]
CLIENTE = config["CLIENTE"]
SUBCANAL = config["SUBCANAL"]
ESTADO = config["ESTADO"]
SUB_CANAL = config["SUB_CANAL"]
N_CLIENTE = config["N_CLIENTE"]
FUNC_IN = config["FUNC_IN"]
FUNC_IN_SELECCIONADAS = config["FUNC_IN_SELECCIONADAS"]
TIPO_Z6 = config["TIPO_Z6"]
TIPO_ZA = config["TIPO_ZA"]
TIPO_Z1 = config["TIPO_Z1"]
ATENCION = config["ATENCION"]
REEMPLAZOS_SOCIOS = config["REEMPLAZOS_SOCIOS"]
REEMPLAZOS_BIBLIA = config["REEMPLAZOS_BIBLIA"]
COLS_DRIVER_EV_NFC = config["COLS_DRIVER_EV_NFC"]
REGION = config["REGION"]
COD_CLI = config["COD_CLI"]
COD_OV = config["COD_OV"]
COD_MT = config["COD_MT"]

CLAVE = config["CLAVE"]
CODIGO = config["CODIGO"]
CN_TIP_LOC = config["CN_TIP_LOC"]
SCN_TIP_LOC = config["SCN_TIP_LOC"]
TIP_LOC = config["TIP_LOC"]
CN_TIP_ORIG = config["CN_TIP_ORIG"]
SCN_TIP_ORIG = config["SCN_TIP_ORIG"]
TIP_ORIG = config["TIP_ORIG"]
FIL_SIN_ASIG = config["FIL_SIN_ASIG"]
FIL_NO = config["FIL_NO"]
FIL_GUION = config["FIL_GUION"]
FIL_NUMERAL = config["FIL_NUMERAL"]
N_IDENT_FI = config["N_IDENT_FI"]
COD_CLI_ORIG = config["COD_CLI_ORIG"]
OFICINA_VENTAS = config["OFICINA_VENTAS"]
RAZON_SOCIAL = config["RAZON_SOCIAL"]
RAZON_SOCIAL_LOC = config["RAZON_SOCIAL_LOC"]
RAZON_SOCIAL_ORIG = config["RAZON_SOCIAL_ORIG"]
NOMBRE_COMERCIAL = config["NOMBRE_COMERCIAL"]
NOMBRE_COMERCIAL_ORIG = config["NOMBRE_COMERCIAL_ORIG"]
NOMBRE_COMERCIAL_LOC = config["NOMBRE_COMERCIAL_LOC"]
COLS_PARA_MERGE_PLANTILLA_2_FINAL = config["COLS_PARA_MERGE_PLANTILLA_2_FINAL"]
COLS_AGRUP_PLANTILLA_3_4_TD_NOTAS_CREDITO = config[
    "COLS_AGRUP_PLANTILLA_3_4_TD_NOTAS_CREDITO"
]
COLS_AGRUP_PLANTILLA_3_4_TD_NOTAS_CREDITO_AGRUP_CONCEP = config[
    "COLS_AGRUP_PLANTILLA_3_4_TD_NOTAS_CREDITO_AGRUP_CONCEP"
]
COLS_FOR_AGRUP_PLN4 = config["COLS_FOR_AGRUP_PLN4"]
COLS_FOR_SUM_PLN4 = config["COLS_FOR_SUM_PLN4"]
COLS_DUPLICAR_PLN4 = config["COLS_DUPLICAR_PLN4"]
VALS_FILTRAR_PLAN4 = config["VALS_FILTRAR_PLAN4"]
COLS_RENOMBRAR_PLANTILLA_3_ACT = config["COLS_RENOMBRAR_PLANTILLA_3_ACT"]
PORCENTAJE_VENTAS_CONTADO_P6 = config["PORCENTAJE_VENTAS_CONTADO_P6"]

VENDEDOR = config["VENDEDOR"]
DEV_MALAS = config["DEV_MALAS"]
ENVIO_DIRECTO = config["ENVIO_DIRECTO"]
VENTA_CONTADO = config["VENTA_CONTADO"]
JEFE_VENTAS = config["JEFE_VENTAS"]
CANAL_TIP = config["CANAL_TIP"]
SUB_CANAL_TIP = config["SUB_CANAL_TIP"]
# Canal Trans.
CANAL_TRANS = config["CANAL_TRANS"]
# Sub Canal Trans.
SUB_CANAL_TRANS = config["SUB_CANAL_TRANS"]
# Segmento Trans.
SEGMENTO_TRANS = config["SEGMENTO_TRANS"]

CATEGORIA = config["CATEGORIA"]
SEGMENTO = config["SEGMENTO"]
TIPOLOGIA = config["TIPOLOGIA"]
CANAL_TIP_AJUST = config["CANAL_TIP_AJUST"]
SUB_CANAL_TIP_AJUST = config["SUB_CANAL_TIP_AJUST"]
TIPOLOGIA_AJUST = config["TIPOLOGIA_AJUST"]
CONCATENADAS = config["CONCATENADAS"]
FORMATO = config["FORMATO"]
FORMATO_ORIG = config["FORMATO_ORIG"]
NOMBRE_FIGURA_COMERCIAL = config["NOMBRE_FIGURA_COMERCIAL"]
DESCRIPCION_CONCEPTO = config["DESCRIPCION_CONCEPTO"]
REAL_ACT = config["REAL_ACT"]
CONCEPTO = config["CONCEPTO"]
COD_CECO = config["COD_CECO"]
COD_KAM = config["COD_KAM"]
COD_JV = config["COD_JV"]
COD_RV = config["COD_RV"]
COD_FC = config["COD_FC"]
DCTO_ANT = config["DCTO_ANT"]
ESCALAS = config["ESCALAS"]
ESCALA = config["ESCALA"]
CANAL_EST = config["CANAL_EST"]
SUB_CANAL_EST = config["SUB_CANAL_EST"]
SECTOR = config["SECTOR"]
SECTOR_1 = config["SECTOR_1"]
SUB_CANAL_TIP_ORIG = config["SUB_CANAL_TIP_ORIG"]
NOMBRE_KAM = config["NOMBRE_KAM"]
GRANDES_CADENAS = config["GRANDES_CADENAS"]
AGRUPACION_CLIENTES = config["AGRUPACION_CLIENTES"]
TIPO_INVERSION = config["TIPO_INVERSION"]
DRIVERS_GENERADOS = config["DRIVERS_GENERADOS"]
DRIVERS_USUARIO = config["DRIVERS_USUARIO"]
COLS_AGRUP_CONS_GASTOS = config["COLS_AGRUP_CONS_GASTOS"]
COLS_AGRUP_CONS_GASTOS_CONCEPTO = config["COLS_AGRUP_CONS_GASTOS_CONCEPTO"]
COLS_AGRUP_PLANTILLA1_TD_D_CLI = config["COLS_AGRUP_PLANTILLA1_TD_D_CLI"]
COLS_AGRUP_PLANTILLA1_TD_VT_DTCOS = config["COLS_AGRUP_PLANTILLA1_TD_VT_DTCOS"]
COLS_AGRUP_PLANT2_P1 = config["COLS_AGRUP_PLANT2_P1"]
COLS_SUM_PLANTILLA1_TD_VD = config["COLS_SUM_PLANTILLA1_TD_VD"]
COLS_SUM_PLANT2_P1 = config["COLS_SUM_PLANT2_P1"]
PLAN_DE_NEGOCIO = config["PLAN_DE_NEGOCIO"]
REORDENAR_COLUMNAS = config["REORDENAR_COLUMNAS"]
# Procesar constantes lectura de maestras de clientes activos e inactivos.
# Invocacion de maestras en insumos p1
MAESTRA_ACTIVOS = INSUMOS[ACTIVOS]
MAESTRA_INACTIVOS = INSUMOS[INACTIVOS]

# Nombres de las maestras
NOM_MAESTRA_ACTIVO = MAESTRA_ACTIVOS[FILE_NAME]
NOM_MAESTRA_INACTIVO = MAESTRA_INACTIVOS[FILE_NAME]
# Nombres de las hojas de cada maestra.
NOM_HOJA_ACTIVO = MAESTRA_ACTIVOS[SHEET]
NOM_HOJA_INACTIVO = MAESTRA_INACTIVOS[SHEET]
# Numero de columnas para ambas maestras
COLS_ACTIVO = MAESTRA_ACTIVOS[COLS]
COLS_INACTIVO = MAESTRA_INACTIVOS[COLS]
# Columnas para selecionar
COLS_ACTIVO_SELECCIONAR = MAESTRA_ACTIVOS[COLS_NECESARIAS]
COLS_INACTIVO_SELECCIONAR = MAESTRA_INACTIVOS[COLS_NECESARIAS]

# Invocacion de socios en insumos p1
BASE_SOCIOS = INSUMOS[SOCIOS]
# Nombre de la base socios.
NOM_BASE_SOCIOS = BASE_SOCIOS[FILE_NAME]
# Nombres de las hojas de base socios.
NOM_HOJA_SOCIOS = BASE_SOCIOS[SHEET]
# Numero de columnas para socios
COLS_SOCIOS = BASE_SOCIOS[COLS]
# Columnas para selecionar
COLS_SOCIOS_SELECCIONAR = BASE_SOCIOS[COLS_NECESARIAS]
# Renombrar columnas socios
SOCIOS_RENOMBRAR = BASE_SOCIOS[RENOMBRAR_COLUMNAS]
# filtrar_subcanal_socios
FIL_SUB_CANAL_SOCIOS = BASE_SOCIOS[FILTRAR_SOCIOS]
# Reemplazos subcanal socios
REEMPLAZOS_SOCIOS_SUBCANAL = BASE_SOCIOS[REEMPLAZOS_SOCIOS]

# Invocacion de Biblia en insumos p1
BASE_BIBLIA = INSUMOS[BIBLIA]
# Nombre de la base biblia.
NOM_BASE_BIBLIA = BASE_BIBLIA[FILE_NAME]
# Nombres de las hojas de base biblia.
NOM_HOJA_BIBLIA = BASE_BIBLIA[SHEET]
# Numero de columnas para biblia
COLS_BIBLIA = BASE_BIBLIA[COLS]
# Columnas para selecionar
COLS_BIBLIA_SELECCIONAR = BASE_BIBLIA[COLS_NECESARIAS]
# Reemplazo biblia
REEMPLAZOS_BIBLIA_SUBCANAL = BASE_BIBLIA[REEMPLAZOS_BIBLIA]

# Invocacion de Estructura_ventas en insumos p1
BASE_ESTRUCTURA_VENTAS = INSUMOS[ESTRUCTURA_VENTAS]
# Nombre de la base Estructura_ventas.
NOM_ESTRUCTURA_VENTAS = BASE_ESTRUCTURA_VENTAS[FILE_NAME]
# Nombres de las hojas de base Estructura_ventas.
NOM_HOJA_ESTRUCTURA_VENTAS = BASE_ESTRUCTURA_VENTAS[SHEET]
# Numero de columnas para Estructura_ventas
COLS_ESTRUCTURA_VENTAS = BASE_ESTRUCTURA_VENTAS[COLS]
# Columnas para selecionar
COLS_ESTRUCTURA_VENTAS_SELECCIONAR = BASE_ESTRUCTURA_VENTAS[COLS_NECESARIAS]
# Renombrar columnas driver_estructura_ventas
COLS_ESTRUCTURA_VENTAS_RENOMBRAR = BASE_ESTRUCTURA_VENTAS[RENOMBRAR_COLUMNAS]
# Columnas estructura de ventas Nombre_Figura_comercial
COLS_EV_FIGURA_COMERCIAL = BASE_ESTRUCTURA_VENTAS[COLS_DRIVER_EV_NFC]

# Invocacion Afo consulta inversion clientes en insumos p2
BASE_AFO_CONSUL_INV = INSUMOS_P2[AFO_CONSUL_INV]
# Nombre de la base
NOM_AFO_CONSUL_INV = BASE_AFO_CONSUL_INV[FILE_NAME]
# Nombres de las hojas de base
NOM_HOJA_AFO_CONSUL_INV = BASE_AFO_CONSUL_INV[SHEET]
# Numero de columnas para Estructura_ventas
COLS_AFO_CONSUL_INV = BASE_AFO_CONSUL_INV[COLS]

RENAME_COLS_AFO_CONSUL_INV = BASE_AFO_CONSUL_INV[RENOMBRAR_COLUMNAS]


BASE_HISTORI_BD_GASTOS = INSUMOS_P2[HISTORI_BD_GASTOS]
# Nombre de la base
NOM_HISTORI_BD_GASTOS = BASE_HISTORI_BD_GASTOS[FILE_NAME]
# Nombres de las hojas de base
NOM_HOJA_HISTORI_BD_GASTOS = BASE_HISTORI_BD_GASTOS[SHEET]
# Numero de columnas para la base
COLS_HISTORI_BD_GASTOS = BASE_HISTORI_BD_GASTOS[COLS]


BASE_ANEXOS = INSUMOS_P2[ANEXOS]
# Nombre de la base
NOM_BASE_ANEXOS = BASE_ANEXOS[FILE_NAME]
# Nombres de las hojas de base
NOM_HOJA_BASE_ANEXOS = BASE_ANEXOS[SHEET]
# Numero de columnas para la base
COLS_ANEXOS = BASE_ANEXOS[COLS]
# Reordenar columnas base anexos
REORDENAR_COLUMNAS_ANEXOS = BASE_ANEXOS[REORDENAR_COLUMNAS]


BASE_MES_ANTERIOR = INSUMOS_P2[BD_CLIENTES_MES_ANT]
# Nombre de la base
NOM_BASE_MES_ANTERIOR = BASE_MES_ANTERIOR[FILE_NAME]
# Nombres de las hojas de base
NOM_HOJA_BASE_MES_ANTERIOR = BASE_MES_ANTERIOR[SHEET]
# Numero de columnas para la base
COLS_BASE_MES_ANTERIOR = BASE_MES_ANTERIOR[COLS]
